mysite/account/urls.py
#!/usr/bin/env python
#-*- coding:utf-8 -*-
from django.conf.urls import url
from . import views
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
   # url(r'^login/$',views.user_login,name='user_login'),
    url(r'^login/$',auth_views.login,name='user_login'),
    url(r'^new_login/$',auth_views.login,{'template_name':'account/login.html'}),
    url(r'^logout/$',auth_views.logout,{'template_name':'account/logout.html'},name='user_logout'),
    url(r'^register/$',views.register,name='user_register'),
    url(r'^password-change/$',auth_views.password_change,{'post_change_redirect': 'account:password_change_done','template_name':'account/password_change_form.html'},name='password_change'),
    url(r'^password-change-done/$',auth_views.password_change_done,{'template_name':'account/password_change_done.html'},name='password_change_done'),
    url(r'^password-reset/$',auth_views.password_reset,{'template_name':'account/password_reset_form.html','email_template_name':'account/password_reset_email.html','subject_template_name':'account/password_teset_subject.txt','post_reset_redirect':'account:password_reset_done'},name='password_reset'),
    url(r'^password-reset-done/$',auth_views.password_reset_done,{'template_name':'account/password_reset_done.html'},name='password_reset_done'),
    url(r'^password-reset-confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',auth_views.password_reset_confirm,{'template_name':'account/password_reset_confirm.html','post_reset_redirect':'account:password_reset_complete'},name='password_reset_confirm'),
    url(r'^password-reset-complete/$',auth_views.password_reset_complete,{'template_name':'account/password_reset_complete.html'},name='password_reset_complete'),
    url(r'^my-information/$',views.myself,name='my_information'),
    url(r'^edit-my-information/$',views.myself_edif,name='edit_my_information'),
]

mysite/article/urls.py
#!/usr/bin/env python
#-*- coding:utf-8 -*-
from django.conf.urls import url
from . import views
from . import list_views


urlpatterns = [
    url(r'^article-column/$',views.article_column,name='article_column'),
    url(r'^rename-column/$',views.rename_article_column,name='rename_article_column'),
    url(r'delete-column',views.del_article_column,name='del_article_column'),
    url(r'^article-post/$',views.article_post,name='article_post'),
    url(r'^article-list/$',views.article_list,name='article_list'),
    url(r'^article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)$',views.article_detail,name='article_detail'),
    url(r'^del-article/$',views.del_article,name='del_article'),
    url(r'^redit-article/(?P<article_id>\d+)$',views.redit_article,name='redit_article'),
    url(r'^list-article-titles/$',list_views.article_titles,name='article_titles'),
    url(r'^list-article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)$',list_views.article_detail,name='list_article_detail'),
    url(r'^list-article-titles/(?P<username>[-\w]+)/$',list_views.article_titles,name='author_articles'),
    url(r'^like-article/$',list_views.like_article,name='like_article'),
    url(r'^article-tag/$',views.article_tag,name='article_tag'),
    url(r'^del-article-tag/$',views.del_article_tag,name='del_article_tag'),
]

mysite/blog/urls.py
#!/usr/bin/env python
#-*- coding:utf-8 -*-
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.blog_title,name='blog_title'),
    url(r'(?P<article_id>\d)/$',views.blog_details,name='blog_detail'),
]

mysite/mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^title/',views.blog_title),
    url(r'^blog/',include('blog.urls',namespace='blog',app_name='blog')),
    url(r'^account/',include('account.urls',namespace='account',app_name='account')),
    url(r'^article/',include('article.urls',namespace='article',app_name='article')),
    url(r'home/',TemplateView.as_view(template_name='home.html'),name='home'),
]

mysite/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
{% include 'header.html' %}
<div class="container">
    {% block content %}{% endblock %}
</div>
{% include 'footer.html' %}
{% block javascript %}{% endblock %}
</body>
</html>

mysite/templates/base_v1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <!--<link rel="stylesheet" href="http://necolas.github.io/normalize.css/">-->
    <!--<link rel='stylesheet' href="http://libs.baidu.com/bootstrap/3.0:3/css/bootstrap.min.css">-->
    <!--<link rel="stylesheet"  type="text/css" href="main.css">-->
    <style>
        .header{
            text-align: center;
            /*color:red;*/
        }
        .content{
            position: relative;
            background-color:yellow;
        }
        .blog_list {
            width: 60%;
            position: relative;
            /*background-color: red;*/
            float: left;
        }

        .propaganda{
            width: 30%;
            position: relative;
            float: left;
            padding-left: 60px;
            padding-top: 30px;
            /*background-color: yellow;*/
        }

        .p1{

        }
    </style>
</head>
<body>
<div class="container">
    {% block content %}
    {% endblock %}
</div>

<!--<script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>-->
<!--<script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>-->
</body>
</html>

mysite/templates/footer.html
<div class="container">
    <hr>
    <p class="text-center">copy right www.itdiffer.com</p>
</div>

mysite/templates/header.html
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="http://www.itdiffer.com"><img src="{% static '/images/logo.png' %}" width="100px"></a>
        </div>
        <div>
            <ul class="nav navbar-nav" role="navigation">
                <li><a href="{% url 'home' %}">HOME</a></li>
                <li><a href="{% url 'blog:blog_title' %}">BLOG</a></li>
                <li><a href="{% url 'article:article_titles'%}">文章</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right: 10px;">
                {% if user.is_authenticated %}
                <li>
                    <div class="dropdown" style="margin-top: 8px;">
                        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu"
                                data-toggle="dropdown">{{ user.username }}<span class="caret"></span></button>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'account:password_change' %}">修改密码</a></li>
                            <li><a href="{% url 'account:my_information' %}">个人信息</a></li>
                        </ul>
                    </div>
                </li>
                <li><a href="#">{{ user.username }}</a></li>
                <li><a href="{% url 'account:user_logout' %}">Logout</a></li>
                {% else%}
                <li><a href="{% url 'account:user_login' %}">LOGIN</a></li>
                <li><a href="{% url 'account:user_register'%}">Sing up</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>

mysite/templates/header_v1.html
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="http://www.itdiffer.com"><img src="{% static '/images/logo.png' %}" width="100px"></a>
        </div>
        <div>
            <ul class="nav navbar-nav" role="navigation">
                <li><a href="{% url 'blog:blog_title' %}">BLOG</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'account:user_login' %}">LOGIN</a></li>
            </ul>
        </div>
    </nav>

</div>

mysite/templates/header_v2.html
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="http://www.itdiffer.com"><img src="{% static '/images/logo.png' %}" width="100px"></a>
        </div>
        <div>
            <ul class="nav navbar-nav" role="navigation">
                <li><a href="{% url 'blog:blog_title' %}">BLOG</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right: 10px;">
                {% if user.is_authenticated %}
                <li><a href="#">{{ user.username }}</a></li>
                <li><a href="{% url 'account:user_logout' %}">Logout</a></li>
                {% else%}
                <li><a href="{% url 'account:user_login' %}">LOGIN</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

</div>

mysite/templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="text-center">
    <h1>WELCOME YOU</h1>
    <h3>life is short.you need happy.</h3>
    <h2>Then you can do everything you want to do and eat every food you like.</h2>
    {% load staticfiles %}
    <img src="{% static 'images/book.jpg'%}">
</div>
{% endblock%}

mysite/templates/paginator.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{page.previous_page_number}}">Previous</a>
        {% endif %}
    <span class="current">
        Page{{page.number}} of {{page.paginator.num_pages}}
    </span>
        {% if page.has_next %}
        <a href="?page={{page.next_page_number}}">Next</a>
        {% endif %}
    </span>
</div>